
# Site
repository: sproogen/resume-theme
favicon: images/favicon

# Content configuration version
version: 2

# Personal info
name: Seunguk Yu
title: NLP Researcher
email: seungukyu@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: seungukyu
linkedin_username: seungukyu

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title:   
about_profile_image: images/seunguk_selfie.jpg
about_content: | # this will include new lines to allow paragraphs
  ìì—°ì–´ì²˜ë¦¬ë¥¼ ì—°êµ¬í•˜ëŠ” ë°•ì‚¬ ê³¼ì • ìœ ìŠ¹ìš±ì…ë‹ˆë‹¤. Offensive Language ë° LLM Safetyë¥¼ ì£¼ë¡œ ìˆ˜í–‰í•´ì™”ìœ¼ë©°, í•œêµ­ì–´ë¥¼ ì‚¬ìš©í•˜ëŠ” ì–´ë– í•œ ìì—°ì–´ì²˜ë¦¬ íƒœìŠ¤í¬ë“  ëª¨ë‘ í° ê´€ì‹¬ì„ ê°€ì§€ê³  ìˆìŠµë‹ˆë‹¤.

  I'm Seunguk Yu, a Ph.D. student working on natural language processing. My main focus has been on offensive language and LLM safety, and I'm really interested in any NLP task involving Korean language.

  âš ï¸ ë°•ì‚¬ ê³¼ì • ìˆ˜ë£Œ í›„ (2027ë…„ ì´í›„) ë°•ì‚¬ í›„ ì „ë¬¸ì—°êµ¬ìš”ì› í¸ì…ì„ í¬ë§í•©ë‹ˆë‹¤. í­ë„“ì€ ìì—°ì–´ì²˜ë¦¬ íƒœìŠ¤í¬ë¥¼ ê¹Šì´ ìˆê²Œ íƒêµ¬í•  ì¤€ë¹„ê°€ ë˜ì–´ ìˆìŠµë‹ˆë‹¤.

content:
  - title:   
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>When the Model Stumbles in Your Domain: Exploring Factual Hallucinations within a Cross-Domain Framework</div>"
        link: # https://aclanthology.org/2025.acl-long.15/
        link_text: "<div style='font-size:0.8em; margin:0;'>link will be updated soon</div>"
        quote: >
          AAAI 2026 under review (first author)
        # description: | # this will include new lines to allow paragraphs
    
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>From Ground Trust to Truth: Disparities in Offensive Language Judgments on Contemporary Korean Political Discourse</div>"
        link: # https://aclanthology.org/2025.acl-long.15/
        link_text: "<div style='font-size:0.8em; margin:0;'>link will be updated soon</div>"
        quote: >
          ğŸ‡¨ğŸ‡³ EMNLP 2025 findings (first author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Delving into Multilingual Ethical Bias: The MSQAD with Statistical Hypothesis Tests for Large Language Models</div>"
        link: https://aclanthology.org/2025.acl-long.15/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          ğŸ‡¦ğŸ‡¹ ACL 2025 main conference (first author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Making Sense of Korean Sentences: A Comprehensive Evaluation of LLMs through KoSEnd Dataset</div>"
        link: https://aclanthology.org/2025.acl-srw.29/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          ğŸ‡¦ğŸ‡¹ ACL 2025 student research workshop (first author)
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>UniGen: Universal Domain Generalization for Sentiment Classification via Zero-shot Dataset Generation</div>"
        link: https://aclanthology.org/2024.emnlp-main.1/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          ğŸ‡ºğŸ‡¸ EMNLP 2024 main (third author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Don't be a Fool: Pooling Strategies in Offensive Language Detection from User-Intended Adversarial Attacks</div>"
        link: https://aclanthology.org/2024.findings-naacl.219/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          ğŸ‡²ğŸ‡½ NAACL 2024 findings (first author)
        # description: | # this will include new lines to allow paragraphs
          

  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Ph.D. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2025 - Present
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ AIëŒ€í•™ì› ì†Œì† ë°•ì‚¬ ê³¼ì •<br>
          <a href="https://sites.google.com/view/iiplcau/home" target="_blank">Intelligent Information Processing Lab</a>, Department of Artificial Intelligence, Chung-Ang University
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: center
        title: "<div style='font-size:0.9em;'>M.S. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2023 - February 2025
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ AIëŒ€í•™ì› ì„ì‚¬ ì¡¸ì—…<br>
          <a href="https://sites.google.com/view/iiplcau/home" target="_blank">Intelligent Information Processing Lab</a>, Department of Artificial Intelligence, Chung-Ang University
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: center
        title: "<div style='font-size:0.9em;'>B.S. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2019 - February 2023
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ ì†Œí”„íŠ¸ì›¨ì–´í•™ë¶€ ì¡¸ì—…<br>
          êµë‚´ ì¸ê³µì§€ëŠ¥ í•™íšŒ CUAI 3,4ê¸° ìš´ì˜<br>
          Department of Computer Science & Engineering, Chung-Ang University<br>
          Led Operations for CUAI, the Campus AI Club for its 3rd and 4rd Terms
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: July - September 2023
        quote: >
          ë©€í‹°ì†ŒìŠ¤ ëŒ€í™” ì±—ë´‡ ì—°êµ¬ ìˆ˜í–‰<br>
          Research on Multi-Source Conversational Chatbots<br>
          <a href="https://langlab.yonsei.ac.kr/" target="_blank">Convei Lab</a> in Yonsei University
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: April - June 2023
        quote: >
          ë‰´ìŠ¤ í¬ë¡¤ë§ ë° í† í”½ ëª¨ë¸ë§ ìˆ˜í–‰<br>
          Worked on News Crawling and Topic Modeling, Jeju University
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: March 2021 - March 2023
        quote: >
          ê°€ì§œ ë‰´ìŠ¤ íƒì§€ ë° ë¬¸ì¥ ë¶„ë¦¬ ê¸°ìˆ  ì—°êµ¬ ìˆ˜í–‰<br>
          Research on Fake News Detection and Sentence Segmentation<br>
          <a href="https://sites.google.com/aicampus.cau.ac.kr/dsl" target="_blank">Data Science Lab</a> in Chung-Ang University
  

  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: July 2025
        quote: >
          KAIST IDEC ìì—°ì–´ì²˜ë¦¬ ê³¼ëª© ì‹¤ìŠµ ì¡°êµ ê·¼ë¬´<br>
          TA for NLP Sessions at KAIST IDEC
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: March - June 2025
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ ì†Œí”„íŠ¸ì›¨ì–´í•™ë¶€ ê³¼ëª© ì˜¤í”ˆì†ŒìŠ¤ì™€SWí”„ë¡œì íŠ¸ ì¡°êµ ê·¼ë¬´<br>
          TA for the Open Source and Software Project, Department of Software at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: April and September 2023
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ êµ°AI êµìœ¡ ê³¼ì • ì‹¤ìŠµ ì¡°êµ ê·¼ë¬´<br>
          TA for the Military AI Training Program at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Coach</div>"
        caption: May and October 2021
        quote: >
          ì£¼ì‹íšŒì‚¬ ì•¨ë¦¬ìŠ¤ AI íŠ¸ë™ 4,5ê¸° ìì—°ì–´ì²˜ë¦¬ ë©˜í† ë¡œì„œ ê°•ì˜ ì§„í–‰<br>
          NLP Mentor for Alice's AI Track 4th and 5th


  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: September 2025
        quote: >
          ì¤‘ì•™ëŒ€í•™êµ AIê¸°ìˆ  ì°½ì—…ê²½ì§„ëŒ€íšŒ ì¥ë ¤ìƒ ìˆ˜ìƒ<br>
          Awarded at the AI Technology Startup Competition at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Paper Award</div>"
        caption: June 2023
        quote: >
          ëŒ€í•œì „ìê³µí•™íšŒ ìš°ìˆ˜í•™ìƒë…¼ë¬¸ìƒ ìˆ˜ìƒ<br>
          Awarded at the Institute of Electronics and Information Engineers (IEIE)
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: December 2021
        quote: >
          ê³¼í•™ê¸°ìˆ ì •ë³´í†µì‹ ë¶€ Open API Contest í•œêµ­ì „ìí†µì‹ ì—°êµ¬ì›ì¥ìƒ ìˆ˜ìƒ<br>
          Awarded at the National AI Research Institute, ETRI
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: October 2021
        quote: >
          KBêµ­ë¯¼ì€í–‰ ì œ3íšŒ Future Finance A.I. Challenge ì „êµ­ ìƒìœ„ 10ê°œ íŒ€ìœ¼ë¡œ ë³¸ì„  ì§„ì¶œ<br>
          Advanced to the Final Competition, ranking among the Top 10 Teams Nationwide

         
  - title: 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP some of my other interests and hobbies are:
      - Workout
      - [Overwatch](https://overwatch.blizzard.com/ko-kr/)
      - Collecting [ShinChan](https://ko.wikipedia.org/wiki/%EC%8B%A0%EC%A7%B1%EA%B5%AC)
      - Food Fighting


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
